#!/bin/bash
echo
echo "   _____            _        _      ____   _____ "
echo "  / ____|          | |      | |    / __ \ / ____|"
echo " | (___   ___   ___| | _____| |_  | |  | | (___  "
echo "  \___ \ / _ \ / __| |/ / _ \ __| | |  | |\___ \ "
echo "  ____) | (_) | (__|   <  __/ |_  | |__| |____) |"
echo " |_____/ \___/ \___|_|\_\___|\__|  \____/|_____/ "
echo
echo "GENERAL SYSTEM INFORMATION"
/usr/bin/screenfetch
echo
